# Generated by Django 5.2.8 on 2025-11-18 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='banner1.png', upload_to='banner', verbose_name='图片')),
                ('order', models.IntegerField(verbose_name='顺序')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name_plural': '轮播图',
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='公告标题')),
                ('content', models.TextField(verbose_name='公告内容')),
                ('igm', models.ImageField(default='notice.png', upload_to='notice', verbose_name='公告图片')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '公告表',
            },
        ),
        migrations.AlterModelOptions(
            name='welcome',
            options={'verbose_name_plural': '欢迎表'},
        ),
    ]
