# Generated by Django 5.2.8 on 2025-12-19 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_area_userinfo_collection_area_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='face_token',
            field=models.CharField(max_length=128, null=True, verbose_name='人脸识别token'),
        ),
    ]
