# Generated by Django 5.2.8 on 2026-01-02 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_collection_face_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notice',
            old_name='igm',
            new_name='img',
        ),
    ]
