# Generated by Django 6.0.4 on 2026-04-25 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_activity_userinfo_mobile_joinrecord_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('camera_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('camera_type', models.SmallIntegerField(choices=[(0, '家庭'), (1, '社区')], verbose_name='摄像头类型')),
                ('camera_name', models.CharField(max_length=50, verbose_name='摄像头名称')),
                ('device_serial', models.CharField(max_length=100, unique=True, verbose_name='设备序列号')),
                ('stream_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='流地址')),
                ('location_desc', models.CharField(blank=True, max_length=100, null=True, verbose_name='位置描述')),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='纬度')),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, verbose_name='经度')),
                ('status', models.SmallIntegerField(choices=[(0, '离线'), (1, '在线')], default=1, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '摄像头',
                'verbose_name_plural': '摄像头',
                'db_table': 'cameras',
            },
        ),
        migrations.CreateModel(
            name='Elder',
            fields=[
                ('elder_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='老人姓名')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='年龄')),
                ('gender', models.SmallIntegerField(blank=True, choices=[(0, '女'), (1, '男')], null=True, verbose_name='性别')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='住址')),
                ('health_notes', models.TextField(blank=True, null=True, verbose_name='健康备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '老人信息',
                'verbose_name_plural': '老人信息',
                'db_table': 'elders',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=255, verbose_name='密码')),
                ('real_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='真实姓名')),
                ('phone', models.CharField(max_length=20, verbose_name='手机号')),
                ('user_type', models.SmallIntegerField(choices=[(1, '管理员'), (2, '家属')], verbose_name='用户类型')),
                ('status', models.SmallIntegerField(choices=[(0, '禁用'), (1, '启用')], default=1, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='FallEvent',
            fields=[
                ('event_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('elder_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='路人姓名')),
                ('is_registered', models.SmallIntegerField(choices=[(0, '未注册'), (1, '已注册')], default=0, verbose_name='是否注册老人')),
                ('fall_time', models.DateTimeField(verbose_name='摔倒时间')),
                ('detect_time', models.DateTimeField(verbose_name='检测时间')),
                ('video_path', models.CharField(blank=True, max_length=255, null=True, verbose_name='视频路径')),
                ('screenshot_path', models.CharField(blank=True, max_length=255, null=True, verbose_name='截图路径')),
                ('confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='AI置信度')),
                ('status', models.SmallIntegerField(choices=[(1, '待处理'), (2, '已处理'), (3, '误报')], default=1, verbose_name='事件状态')),
                ('processed_by', models.BigIntegerField(blank=True, null=True, verbose_name='处理人ID')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('process_notes', models.TextField(blank=True, null=True, verbose_name='处理备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('camera', models.ForeignKey(db_column='camera_id', on_delete=django.db.models.deletion.CASCADE, to='myapp.camera', verbose_name='关联摄像头')),
                ('elder', models.ForeignKey(blank=True, db_column='elder_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.elder', verbose_name='关联老人')),
            ],
            options={
                'verbose_name': '摔倒事件',
                'verbose_name_plural': '摔倒事件',
                'db_table': 'fall_events',
            },
        ),
        migrations.CreateModel(
            name='AlertLog',
            fields=[
                ('alert_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('recipient_id', models.BigIntegerField(verbose_name='接收人ID')),
                ('recipient_type', models.SmallIntegerField(choices=[(1, '家属'), (2, '管理员')], verbose_name='接收人类型')),
                ('recipient_phone', models.CharField(max_length=20, verbose_name='接收手机号')),
                ('send_method', models.SmallIntegerField(choices=[(1, '短信'), (2, 'APP推送'), (3, '电话')], verbose_name='发送方式')),
                ('send_status', models.SmallIntegerField(choices=[(0, '失败'), (1, '成功'), (2, '发送中')], default=1, verbose_name='发送状态')),
                ('error_msg', models.CharField(blank=True, max_length=255, null=True, verbose_name='错误信息')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='发送时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('event', models.ForeignKey(db_column='event_id', on_delete=django.db.models.deletion.CASCADE, to='myapp.fallevent', verbose_name='关联摔倒事件')),
            ],
            options={
                'verbose_name': '告警日志',
                'verbose_name_plural': '告警日志',
                'db_table': 'alert_logs',
            },
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('relation_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('relationship', models.CharField(blank=True, max_length=20, null=True, verbose_name='关系')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('elder', models.ForeignKey(db_column='elder_id', on_delete=django.db.models.deletion.CASCADE, to='myapp.elder', verbose_name='关联老人')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='myapp.user', verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '家属-老人关系',
                'verbose_name_plural': '家属-老人关系',
                'db_table': 'relations',
                'unique_together': {('elder', 'user')},
            },
        ),
    ]
